services:
  - type: web
    name: spot-ai-trader
    env: python
    pythonVersion: 3.10.13
    buildCommand: pip install -r requirements.txt
    startCommand: python3 agent.py
    healthCheckPath: /
    envVars:
      - key: RUN_DASHBOARD
        value: "0"
      - key: DATABASE_URL
        fromDatabase:
          name: spot-ai-db
          property: connectionString
      - key: DATA_DIR
        value: /var/data
    disks:
      - name: trade-data
        mountPath: /var/data
        sizeGB: 1
  - type: web
    name: spot-ai-dashboard
    env: python
    pythonVersion: 3.10.13
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run dashboard.py --server.port $PORT --server.headless true
    healthCheckPath: /
    envVars:
      - key: DATA_DIR
        value: /var/data
    disks:
      - name: trade-data
        mountPath: /var/data
        sizeGB: 1
databases:
  - name: spot-ai-db
    plan: free
